variable "event_name" {
  type        = string
  description = "Name of the Cloudwatch Event"
  default     = ""
}
variable "display_name" {
  type        = string
  description = "The display name for the topic"
  default     = ""
}
variable "sns_key_alias" {
  description = "alias of the KMS Key for encrypting SNS."
  type        = string
  default     = "sns-key"
}
variable "sns_subscription" {
  description = "Map of SNS subscriptions, keyed by endpoint."
  type = map(object({
    endpoint = string
  }))
  default = null
}
variable "event_patterns" {
  description = "Map of event patterns for CloudWatch events"
  type = map(object({
    description   = string
    event_pattern = string
  }))
  default = null
}
variable "lambda_function_name" {
  type        = string
  description = "Unique name for your Lambda Function"
  default     = ""
}
variable "lambda_filename" {
  type        = string
  description = "Path to the function's deployment package within the local filesystem"
  default     = ""
}
variable "lambda_handler" {
  type        = string
  description = "Function entrypoint in your code"
  default     = "RootActivityLambda.lambda_handler"
}
variable "lambda_runtime" {
  type        = string
  description = "Identifier of the function's runtime. See Runtimes for valid values"
  default     = "python3.8"
}
variable "lambda_timeout" {
  type        = number
  description = "Amount of time your Lambda Function has to run in seconds."
  default     = 60
}
variable "lambda_statement_id" {
  type        = string
  description = "A unique statement identifier. By default generated by Terraform"
  default     = "AllowExecutionFromCloudWatch"
}
variable "lambda_action" {
  type        = string
  description = "The AWS Lambda action you want to allow in this statement."
  default     = "lambda:InvokeFunction"
}
variable "lambda_principal" {
  type        = string
  description = "The principal who is getting this permission."
  default     = "events.amazonaws.com"
}
variable "retention_in_days" {
  type        = number
  description = "Specifies the number of days you want to retain log events in the specified log group."
  default     = 30
}
variable "cloudwatch_key_alias" {
  description = "alias of the KMS Key for encrypting Cloudwatch logs."
  type        = string
  default     = "cloudwatch-logs-key"
}
variable "deletion_key_window_in_days"{
  description = "The waiting period, specified in number of days."
  type        = number
  default     = 7 
}
